server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/moviesearcher
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

jwt:
  secret: "myjwtsecretkeyforlocaldev1234567890"
  expiration: 3600000

tmdb:
  api:
    base-url: https://api.themoviedb.org/3
    key: 27c61a0fb8e79d5d69d037b47657fc68
    image-base-url: https://image.tmdb.org/t/p/w500

# 로깅 설정
logging:
  level:
    com.moviesearcher: DEBUG
    org.springframework.web: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n" 