version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: moviesearcher-postgres
    environment:
      POSTGRES_DB: moviesearcher_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - moviesearcher-network

  redis:
    image: redis:7-alpine
    container_name: moviesearcher-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - moviesearcher-network

volumes:
  postgres_data:
  redis_data:

networks:
  moviesearcher-network:
    driver: bridge 